### ISSUE TITLE
No Link to the Finished Compiled Program

### ISSUE THREAD

**Issue by choppergirl** [adocilesloth/SRBeep#12]
I don't see a link to a zip file to download containing the compiled plugin and resouces... at all?  Am I missing something?

All I see are some source code, header files, and the mp3 files... and no idea how to recreate any directory structure.

Maybe I'm missing the link somewhere to download the zip file of the finished compiled Windows  files to merge with the obs-studio folder?

No link to contact the author and ask him either?   

choppergirl@air-war.org

**Comment by adocilesloth** [comment]
There is a zip file with the compiled plugin and resources on the Releases page in the repo. Alternativly, click here:
https://github.com/adocilesloth/SRBeep/releases/tag/v2.1.0

If that works, please close the issue (it has been a while since I posted the release so can't quite remember what's in it)

I get notifications when people post issues. Iwould also not reccomend posting your email address on an open forum.

**Comment by choppergirl** [comment]
Ok, thanks.   I don't see that the download was self evident anywhere.   I'm struggling right now for 30 minutes trying to figure out how to close this issue????

Maybe you should make a home page for your software like do, and host it on your own server, instead of using this F'd up Github repository system.  I tried to use Github a few weeks ago to host my own software and ran into the 25mb file length limit myself and was like oh bump this, this is useless. My file was 25.6mb.    

As soon as I figure out how to close this issue, I will.  Clicking on the "open" button seems to do nothing.   Give me a some moments...  to google this nonintuitive Github UI mess.   

Okay, well, there you go, its in the Post Comment location of all !@#$% places.  That makes no sense.

Thanks again... happy coding... 
Choppergirl
[http://soundpack.air-war.org](http://soundpack.air-war.org)
[http://edgy.air-war.org](http://edgy.air-war.org)
