### ISSUE TITLE
Use the plugin template

### ISSUE THREAD

**Issue by CodeYan01** [adocilesloth/SRBeep#19]
You should use the [plugin template](https://github.com/obsproject/obs-plugintemplate), as it lets you generate releases with installers. This would reduce user error when extracting the plugin zips.

**Comment by adocilesloth** [comment]
I probably should but I'm not going to. This project is older than the template and I have neither the time nor inclination to rewrite it because people don't understand how file structures work. I also know it would mean that there is also a mac release but again, I lack the time and motivation to do so.
